version: "3.1"

services:
  start-project_db:
    container_name: start-project_db
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: start-project
      POSTGRES_USER: start-project
      POSTGRES_PASSWORD: s3cr3t
    volumes:
      - local_start-project_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  local_start-project_db:
